"""create Tables

Revision ID: ece9cf494889
Revises: 
Create Date: 2023-03-24 22:23:38.372867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece9cf494889'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_changes',
    sa.Column('id_changes', sa.Integer(), nullable=False),
    sa.Column('dite_changes', sa.DateTime(), nullable=True),
    sa.Column('log_change', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_changes')
    )
    op.create_table('raw_data',
    sa.Column('id_data', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('img_href', sa.String(), nullable=True),
    sa.Column('net_href', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_data')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_data')
    op.drop_table('log_changes')
    # ### end Alembic commands ###
